package com.amnex.agristack.Enum;

public enum ErrorCode {

	VERSION_MISMATCH(1111),
	APP_SIGNED(2222),
	MAXIMUM_AREA_DISTANCE_CHECK(333),
	TOO_MANY_REQUESTS(429),
	CROP_MEDIA_CHECK_NULL(101),
	UNUTILIZED_MEDIA_CHECK_NULL(102),
	WASTE_OR_VACANT_MEDIA_CHECK_NULL(103),
	HARVESTED_MEDIA_CHECK_NULL(104),
	MEDIA_CHECK_NULL(105),
	LAND_ASSIGNMENT_CHECK_NOT_FOUND(106),
	REVIEW_NO_CHECK_ZERO(107),
	REVIEW_NO_CHECK_IN_VALID(108),
	AREA_CHECK_NOT_VALID(109),
	UPLOADING_MEDIA_ERROR(110),
	TOKEN_CHECK_NULL(111),
	UNIQUE_CHECK_DB(112),
	PLAY_RECOGNIZED_CHECK(113),
	APP_PACKAGE_CHECK(114),
	APP_CERTIFICATE_CHECK_MISMATCH(115),
	GEO_LOCATION_CHECK_INVALID(116),
	CHECK_ACTIVE_SEASON(118);
	   private final int numericalCode;

	    private ErrorCode(int numericalCode) {
	        this.numericalCode = numericalCode;
	    }

	    public int getNumericalCode() {
	        return numericalCode;
	}

}
