package com.amnex.agristack.Enum;

public enum MenuCodeEnum {
    DASHBOARD(200),
    USER_MANAGEMENT(201),
    ROLE_MANAGEMENT(202),
    SURVEY_MANAGEMENT(203),
    CONFIGURATION(204),
    SEASON_MASTER(205),
    MY_PROFILE(206),
	ADMINISTRATIVE_LAND(207),
	REGISTRY(208),
	VERIFIER_MANAGEMENT(209),
	SUPERVISOR_MANAGEMENT(210),
	PAYMENT_MANAGEMENT(211),
	REPORT_MANAGEMENT(212),
	GRIEVANCE_MANAGEMENT(213),
	WORKFLOW_DETAILS(214),
    EARLY_LATE_SEASON_CONFIGURATION(215),
    SUB_REPORT_MANAGEMENT(216),
    CROP_VARIETIES(217),
	CROP_CATEGORIES(218),
	NON_AGRICULTURE_PLOTS(219),
    SURVEY_ACTIVITY_CONFIGURATION(220),
    ADD_CROP_SURVEYOR(221),
	PR_REQUEST_APPROVAL(222),
	SURVEYOR_ALLOCATION(223),
    OBJECT_HANDLING(224),
    VILLAGE_WISE_CROP_SURVEY(225),
    MANDATORY_SURVEY_PER_TERRITORY(229),
    PR_PAYMENT_RELEASE(232),
    USER_MANAGEMENT_USER(226),
    USER_MANAGEMENT_USER_ROLE(227),
    USER_MANAGEMENT_ROLE_MANAGEMENT(228),
    SUPERVISOR_TASK_ALLOCATION(234),
    REVIEW_SURVEY_DETAIL(235),
    CROP_MASTER(237);
	
    private int value;

    MenuCodeEnum(int value) {
    	this.value = value;
    }
}